# Generated by Django 4.0.2 on 2022-08-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='industry_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='core.industrytype'),
        ),
    ]
